version: 2

project_name: terraform-provider-remote

builds:
  - goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: "-s -w"

archives:
  - format: zip

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
    cmd: gpg
    args: ["--detach-sign", "--armor", "--local-user", "{{ .Env.GPG_FINGERPRINT }}", "--output", "checksums.txt"]
    stdin: false
    env:
      - GPG_FINGERPRINT
    #16AE97A8A5E637D0
release:
  github:
    owner: unlimitechcloud
    name: terraform-provider-remote
