version: 2

project_name: terraform-provider-remote

builds:
  - goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: "-s -w"

archives:
  - format: zip

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
    args: ["--armor", "--detach-sign"]
    cmd: gpg
    env:
      - GPG_FINGERPRINT
    #195DB3EDF551968F4CCB3F5716AE97A8A5E637D0
    
release:
  github:
    owner: unlimitechcloud
    name: terraform-provider-remote
